"""描述您的变更

Revision ID: 040a3dad5962
Revises: a1b2c3d4e5f6
Create Date: 2025-05-26 00:21:15.312467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '040a3dad5962'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resources', sa.Column('likes_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resources', 'likes_count')
    # ### end Alembic commands ### 